# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=5000, null=True)),
                ('email', models.TextField(blank=True, max_length=5000, null=True)),
                ('phone', models.TextField(blank=True, max_length=5000, null=True)),
                ('dob', models.TextField(blank=True, max_length=5000, null=True)),
                ('sharing', models.TextField(blank=True, max_length=5000, null=True)),
                ('suggestions', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
