# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=5000)),
                ('email', models.TextField(max_length=5000)),
                ('phone', models.TextField(max_length=5000)),
                ('dob', models.TextField(max_length=5000)),
                ('t_h', models.TextField(max_length=5000)),
                ('food', models.TextField(max_length=5000)),
                ('song', models.TextField(max_length=5000)),
                ('fav_place', models.TextField(max_length=5000)),
                ('fav_person', models.TextField(max_length=5000)),
                ('jail', models.TextField(max_length=5000)),
                ('invisible', models.TextField(max_length=5000)),
                ('memory', models.TextField(max_length=5000)),
                ('wish', models.TextField(max_length=5000)),
                ('best_thing', models.TextField(max_length=5000)),
                ('worst_thing', models.TextField(max_length=5000)),
                ('rating', models.TextField(max_length=5000)),
                ('advice', models.TextField(max_length=5000)),
            ],
        ),
    ]
